# Gitleaks configuration file

title = "Touchless Interaction Security Scan"

# Define global rules
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '(?i)(api[_-]?key|apikey|api[_-]?token)[=:]["\'']?([0-9a-zA-Z]{32,45})["\'']?'
tags = ["key", "API", "generic"]
severity = "HIGH"

[[rules]]
id = "password-in-code"
description = "Password in code"
regex = '(?i)(password|passwd|pwd)[=:]["\'']?([0-9a-zA-Z!@#$%^&*()_+]{8,})["\'']?'
tags = ["credentials", "password"]
severity = "HIGH"

# Allow specific files/folders to be ignored
[allowlist]
paths = [
    "secrets/.*",
    ".*\\.md$"
]
