
services:
  touchless-interaction:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "10000-10100:10000-10100/udp" 
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      - TZ=UTC
      - API_KEY=${API_KEY}
      - APP_SECRET=${APP_SECRET}

